components/furnituremix/frontend/src/app/core/UseCases.ts, components/furnituremix/frontend/src/app/core/components/banner.tsx, components/furnituremix/frontend/src/app/core/components/embed.tsx, components/furnituremix/frontend/src/app/core/components/grid-item.tsx, components/furnituremix/frontend/src/app/core/components/slider.tsx, components/furnituremix/frontend/src/app/routes/index.tsx, components/furnituremix/frontend/src/app/routes/shop/$folder.$product.tsx, components/furnituremix/frontend/src/app/routes/shop/$folder.tsx, components/furnituremix/frontend/src/app/routes/stories/$story.tsx, components/furnituremix/frontend/src/app/routes/stories/index.tsx
=> Bug fix for frontend previews

components/furnituremix/frontend/src/app/core/components/cart.tsx, components/furnituremix/frontend/src/app/core/components/checkout-forms/cart.tsx, components/furnituremix/frontend/src/app/core/components/checkout-forms/guest.tsx, components/furnituremix/frontend/src/app/core/components/checkout-forms/register.tsx, components/furnituremix/frontend/src/app/core/components/topic-navigation.tsx, components/furnituremix/frontend/src/app/routes/checkout.tsx, components/furnituremix/frontend/src/app/routes/shop/$folder.$product.tsx
=> checkout and navigation fix

components/furnituremix/frontend/src/app/core/components/cart.tsx
=> add to cart notification position fxied instead of absolute

components/furnituremix/frontend/src/app/core/components/header.tsx, components/furnituremix/frontend/src/app/core/components/price.tsx, components/furnituremix/frontend/src/app/core/components/stock-location.tsx, components/furnituremix/frontend/src/app/core/components/topic-labels.tsx, components/furnituremix/frontend/src/app/core/use-cases/crystallize/index.ts, components/furnituremix/frontend/src/app/routes/index.tsx, components/furnituremix/frontend/src/app/routes/shop/$folder.$product.tsx, components/furnituremix/frontend/src/app/routes/shop/$folder.tsx, components/furnituremix/frontend/src/app/routes/shop/index.tsx, components/furnituremix/frontend/src/app/routes/stories/$story.tsx, components/furnituremix/frontend/src/app/routes/stories/index.tsx
| Branch?       | feature/meta
=> add structured data

components/furnituremix/frontend/src/app/core/components/search/index.tsx
| Branch?       | bug-fix/search
=> search fix

components/furnituremix/frontend/src/app/core/components/cart.tsx, components/furnituremix/frontend/src/app/core/components/crystallize-components/dimensions-table.tsx, components/furnituremix/frontend/src/app/core/components/crystallize-components/paragraph-collection.tsx, components/furnituremix/frontend/src/app/core/components/item/product.tsx, components/furnituremix/frontend/src/app/core/components/price.tsx, components/furnituremix/frontend/src/app/lib/pricing.tsx, components/furnituremix/frontend/src/app/routes/orders.tsx, components/furnituremix/frontend/src/app/routes/shop/$folder.$product.tsx, components/furnituremix/frontend/src/app/styles/index.css, components/furnituremix/frontend/src/app/styles/tailwind/default.js
| Branch?       | feature/my-account
=> add currency formatter and my account page

components/furnituremix/frontend/src/app/core/components/crystallize-components/paragraph-collection.tsx, components/furnituremix/frontend/src/app/core/components/item/product.tsx, components/furnituremix/frontend/src/app/core/components/tiles/embed.tsx, components/furnituremix/frontend/src/app/core/components/variant-selector.tsx, components/furnituremix/frontend/src/app/routes/shop/$folder.$product.tsx, components/furnituremix/frontend/src/app/styles/index.css
=> responsive fixes for products

components/furnituremix/frontend/src/app/core/use-cases/crystallize/index.ts, components/furnituremix/frontend/src/app/routes/$topic.$child.tsx
| Branch?       | bugfix/topics
=> update topic thing

components/furnituremix/frontend/src/app/core/components/grid-cells/grid.tsx, components/furnituremix/frontend/src/app/core/components/tiles/banner.tsx, components/furnituremix/frontend/src/app/core/use-cases/crystallize/index.ts, components/furnituremix/frontend/src/app/lib/grid-tile/grid.tsx, components/furnituremix/frontend/src/app/styles/index.css
=> first go at enabling background video and images

components/furnituremix/frontend/src/app/core/components/tiles/banner.tsx
=> fixed a image issue for banners

components/furnituremix/frontend/src/app/core/components/cart.tsx, components/furnituremix/frontend/src/app/core/components/checkout-forms/cart.tsx, components/furnituremix/frontend/src/app/core/components/header.tsx, components/furnituremix/frontend/src/app/core/components/variant-selector.tsx, components/furnituremix/frontend/src/app/lib/pricing/pricing-component.tsx, components/furnituremix/service-api/src/routes/payment.ts
| Branch?       | develop / venkel-fixes
=> venkel specific changes

components/furnituremix/frontend/src/app/routes/about-us/$document.tsx, components/furnituremix/frontend/src/app/routes/about-us/index.tsx
| Branch?       | develop / friio-fixes
=> add about-us

components/furnituremix/application/src/app/core/components/header.tsx, components/furnituremix/application/src/app/core/components/search/index.tsx
| Branch?       | allinoneremix / currency-fix
=> currency fix

components/furnituremix/application/src/app/core/components/filter/filtered-products.tsx, components/furnituremix/application/src/app/core/components/header.tsx, components/furnituremix/application/src/app/core/components/item/curated-product.tsx, components/furnituremix/application/src/app/core/components/item/product.tsx, components/furnituremix/application/src/app/core/components/variant-selector.tsx, components/furnituremix/application/src/app/core/use-cases/crystallize/index.ts, components/furnituremix/application/src/app/routes/shop/$folder.tsx, components/furnituremix/application/src/app/routes/stories/curated-product-story.tsx, components/furnituremix/application/src/app/styles/index.css
| Branch?       | main / bug-fixes
| Fixed tickets | 
[sc-6652]
[sc-6647]
[sc-6643]
[sc-6682]
[sc-6684]
=> bug fixes and improvements

components/furnituremix/application/src/app/core-server/storage.server.ts, components/furnituremix/application/src/app/core/components/header.tsx, components/furnituremix/application/src/app/core/use-cases/crystallize/index.ts, components/furnituremix/application/src/app/root.tsx
Story details: https://app.shortcut.com/crystallize/story/6265
=> feat: [sc-6265] Performance feedback based on a quick look at <https://pewag-racing-team.superfast.store/>:

components/furnituremix/application/.env.dist, components/furnituremix/application/src/app/routes/shop/$folder.$product.tsx, components/furnituremix/application/src/app/routes/shop/$folder.tsx
| Branch?       | main / quick-fix
=> quick fix for title and change env var name

components/furnituremix/application/src/app/core/components/item/curated-product.tsx, components/furnituremix/application/src/app/core/components/item/product.tsx
=> fixed product heights in grids and listing

components/furnituremix/application/package-lock.json, components/furnituremix/application/package.json, components/furnituremix/application/src/app/lib/image/favicon.tsx, components/furnituremix/application/src/app/root.tsx, components/furnituremix/application/src/app/routes/favicon/$size[.png].ts
Story details: https://app.shortcut.com/crystallize/story/6112
Dynamic route to render favicon by size from logo.
TODO:
=> feat: [sc-6112] Manage the favicon.ico and similar per tenant.

components/furnituremix/application/src/app/core/components/crystallize-components/paragraph-collection.tsx, components/furnituremix/application/src/app/core/use-cases/crystallize/index.ts, components/furnituremix/application/src/app/routes/shop/index.tsx, components/furnituremix/application/src/app/routes/stories/$document.tsx, components/furnituremix/application/src/app/styles/index.css
| Branch?       | develop / design/story
=> reduced spacing on paragraphs and sizing on images

components/furnituremix/application/src/app/core/components/grid-cells/grid.tsx, components/furnituremix/application/src/app/core/components/item/curated-product.tsx, components/furnituremix/application/src/app/core/components/item/document.tsx, components/furnituremix/application/src/app/core/use-cases/crystallize/index.ts, components/furnituremix/application/src/app/lib/grid-tile/grid.tsx, components/furnituremix/application/src/app/lib/grid-tile/types.ts, components/furnituremix/application/src/app/routes/index.tsx, components/furnituremix/application/src/app/routes/shop/$folder.$product.tsx, components/furnituremix/application/src/app/routes/shop/index.tsx, components/furnituremix/application/src/app/routes/stories/$document.tsx, components/furnituremix/application/src/app/routes/stories/index.tsx
| Branch?       | develop / new-content-model
| BC breaks?    | yes
=> changes reflecting new content model

components/furnituremix/application/src/app/core/components/pdf/order-invoice.tsx, components/furnituremix/application/src/app/routes/api/webhook/order/created.tsx
=> ui changes

components/furnituremix/application/src/app/core-server/authentication.server.ts, components/furnituremix/application/src/app/core/components/checkout-forms/address.tsx, components/furnituremix/application/src/app/core/components/filter/attribute-filter.tsx, components/furnituremix/application/src/app/core/components/filter/filtered-products.tsx, components/furnituremix/application/src/app/core/components/filter/index.tsx, components/furnituremix/application/src/app/core/components/input.tsx, components/furnituremix/application/src/app/core/components/item/curated-product.tsx, components/furnituremix/application/src/app/routes/shop/$folder.tsx, components/furnituremix/application/src/app/routes/stories/curated-product-story.tsx, components/furnituremix/application/src/app/use-cases/crystallize/fetchPriceRangeAndAttributes.ts, components/furnituremix/application/src/app/use-cases/crystallize/index.ts, components/furnituremix/application/src/app/use-cases/crystallize/pushOrder.server.ts, components/furnituremix/application/src/app/use-cases/crystallize/searchOrderBy.ts
| Branch?       | main / feature-attribute-filter
| Fixed tickets |
=> add attribute filter [sc-6330]

components/furnituremix/application/src/app/core/components/product-body.tsx, components/furnituremix/application/src/app/core/components/tiles/banner.tsx, components/furnituremix/application/src/app/core/components/tiles/embed.tsx, components/furnituremix/application/src/app/core/components/tiles/slider.tsx, components/furnituremix/application/src/app/lib/linkRenderer.tsx, components/furnituremix/application/src/app/routes/shop/$folder.$product.tsx
| Fixed tickets | [sc-7475] [sc-7473]
=> bug fixes and cleanup [sc-7475] [sc-7473]

components/furnituremix/application/src/app/core/components/crystallize-components/paragraph-collection.tsx, components/furnituremix/application/src/app/core/components/files.tsx, components/furnituremix/application/src/app/core/components/filter/attribute-filter.tsx, components/furnituremix/application/src/app/core/components/filter/index.tsx, components/furnituremix/application/src/app/core/components/footer.tsx, components/furnituremix/application/src/app/root.tsx
=> fix CLS issue and minor cleanup

components/furnituremix/application/src/app/core/components/crystallize-components/files.tsx, components/furnituremix/application/src/app/core/components/header.tsx, components/furnituremix/application/src/app/core/components/product-body.tsx, components/furnituremix/application/src/app/routes/stories/curated-product-story.tsx
=> Limit curated product image size [sc-7529]

components/furnituremix/application/src/app/core/components/filter/filtered-products.tsx, components/furnituremix/application/src/app/core/components/item/product.tsx, components/furnituremix/application/src/app/core/components/tiles/banner.tsx, components/furnituremix/application/src/app/core/components/tiles/slider.tsx, components/furnituremix/application/src/app/routes/$topic.$child.tsx, components/furnituremix/application/src/app/routes/stories/curated-product-story.tsx
| Branch?       | main
| Fixed tickets | NA
=> cleanup and minor css changes

components/furnituremix/application/src/app/core/components/pdf/folder.tsx, components/furnituremix/application/src/app/core/components/pdf/shared.tsx, components/furnituremix/application/src/app/core/components/pdf/single-product.tsx, components/furnituremix/application/src/app/core/components/pdf/styles.js, components/furnituremix/application/src/app/core/components/variant-selector.tsx, components/furnituremix/application/src/app/routes/shop/$folder.$product.tsx, components/furnituremix/application/src/app/routes/shop/$folder[.]pdf.tsx, components/furnituremix/application/src/app/use-cases/crystallize/searchOrderBy.ts
=> pdf designs

components/furnituremix/application/src/app/core/components/item/product.tsx, components/furnituremix/application/src/app/use-cases/crystallize/fetchNavigation.ts, components/furnituremix/application/src/app/use-cases/crystallize/searchByTopic.ts
| Branch?       | main
| Fixed tickets |  [sc-7632]
=> add attributes to product list view

components/furnituremix/application/src/app/lib/createGrid.tsx, components/furnituremix/application/src/app/routes/shop/$folder.tsx, components/furnituremix/application/src/app/routes/shop/index.tsx, components/furnituremix/application/src/app/use-cases/crystallize/fetchFolder.ts
| Branch?       | main
| Fixed tickets | [sc-7110]
=> add support for tile stacks and single tiles on folder [sc-7110]

components/furnituremix/application/src/app/core/components/tiles/banner.tsx, components/furnituremix/application/src/app/routes/index.tsx, components/furnituremix/application/src/app/routes/shop/$folder.tsx
=> support for video on banner [sc-8255]

components/furnituremix/application/src/app/core/components/tiles/banner.tsx
=> Update banner.tsx [sc-8304]

components/furnituremix/application/src/app/styles/index.css
=> add styling for list

components/furnituremix/application/src/app/core/components/add-to-cart-button.tsx, components/furnituremix/application/src/app/core/pages/Product.tsx, components/furnituremix/application/src/app/root.tsx
=> add canonical link and disable add to cart button when product out of stock [sc-8367] [sc-8374]

components/content-commerce/pages/shop/[product].js
=> added related products to product pages

components/furnituremix/application/src/core/components/item/product.tsx, components/furnituremix/application/src/core/components/language-switcher.tsx, components/furnituremix/application/src/core/components/search/index.tsx, components/furnituremix/application/src/core/components/topic-navigation.tsx
=> accessibility fixes

components/furnituremix/application/src/ui/components/layout/footer.tsx, components/furnituremix/application/src/use-cases/contracts/Footer.ts, components/furnituremix/application/src/use-cases/mapper/API/fetchFooterToFooter.ts, components/furnituremix/provisioning/tenant/spec.json
=> change url to link

components/furnituremix/application/src/ui/components/category-list.tsx, components/furnituremix/application/src/use-cases/mapper/API/fetchFolderToCategory.ts, components/furnituremix/application/src/use-cases/mapper/API/fetchFolderWithChildrenToCategoryWithChildren.ts, components/furnituremix/application/src/use-cases/mapper/API/fetchShopToShop.ts
=> internal server error on categories fix

components/furnituremix/application/src/ui/components/grid/tiles/banner.tsx, components/furnituremix/application/src/ui/components/grid/tiles/embed.tsx, components/furnituremix/application/src/ui/components/grid/tiles/slider.tsx, components/furnituremix/application/src/ui/lib/grid-tile/grid.tsx
| Branch?       | main / cta-check-fix
| Fixed tickets | [sc-8303]
=> add check to tile CTA

components/furnituremix/application/src/routes/$langstore/shop/$folder.$product.tsx, components/furnituremix/application/src/ui/components/crystallize-components/paragraph-collection.tsx, components/furnituremix/application/src/ui/components/grid/tiles/banner.tsx, components/furnituremix/application/src/use-cases/contracts/Video.ts, components/furnituremix/application/src/use-cases/crystallize/read/fetchProduct.ts, components/furnituremix/application/src/use-cases/mapper/API/fetchProductToProduct.ts, components/furnituremix/application/src/use-cases/mapper/Object/APIVideoToVideo.ts, components/furnituremix/application/src/use-cases/mapper/index.ts
| Branch?       | main / video-support-paragraph-collection
| Fixed tickets | [sc-9396]
=> add support for videos on products
